# Generated by Django 6.0.3 on 2026-03-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_exchangerequest_completed_at_exchangerequest_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('music', 'Music'), ('cooking', 'Cooking'), ('tutoring', 'Tutoring'), ('crafts', 'Crafts'), ('language', 'Language'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
